apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-s3-config
  namespace: factory-s3-store
data:
  application.properties: |
    
    kafka.broker.uri=kafka-cluster-kafka-bootstrap.factory-s3-store.svc:9092
    kafka.broker.topic.temperature=manuela-factory.iot-sensor-sw-temperature
    kafka.broker.topic.vibration=manuela-factory.iot-sensor-sw-vibration

    s3.region={{ .Values.global.s3.bucket.region }}
    s3.bucket.name={{ .Values.global.s3.bucket.name }}
    s3.message.aggregation.count={{ .Values.global.s3.bucket.message.aggregation.count }}
    s3.custom.endpoint.enabled={{ .Values.global.s3.bucket.custom.endpoint.enabled }}
    # Convert this directory into a helm chart and use templating to set this
    s3.custom.endpoint.url=s3-openshift-storage.apps.{{ .Values.global.localClusterDomain }}

    
