apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messaging
  name: messaging
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: messaging
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - image: {{ .Values.iot_consumer.image_location }}:{{ .Values.iot_consumer.tag }}
        imagePullPolicy: Always
        name: messaging
        ports:
        - containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: messaging-configmap
        - secretRef:
            name: messaging-secret
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

