apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: machine-sensor-2
    template: openjdk18-web-basic-s2i
    app.kubernetes.io/part-of: ManuELA
  name: machine-sensor-2
  namespace: manuela-stormshift-machine-sensor
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deploymentConfig: machine-sensor-2
  template:
    metadata:
      creationTimestamp: null 
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/machine-sensor/machine-sensor-2-configmap.yaml") . | sha256sum }}
      labels:
        application: machine-sensor-2
        deploymentConfig: machine-sensor-2
      name: machine-sensor-2
    spec:
      containers:
      - name: machine-sensor
        image: machine-sensor:latest
        #imagePullPolicy: Always
        ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
        envFrom:
          - configMapRef: 
              name: machine-sensor-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe: 
          httpGet:   
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15  
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
