apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
  labels:
    app: "camel-k"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configuration:
  - type: repository
    value: https://maven.repository.redhat.com/ga/all@id=redhat.ea
  build:
    registry:
      address: image-registry.openshift-image-registry.svc:5000
      secret: ocp-registry
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-operator-registry-editor
  namespace: manuela-data-lake
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: manuela-data-lake
roleRef:
  kind: ClusterRole
  name: registry-editor
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-operator-registry-viewer
  namespace: manuela-data-lake
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: manuela-data-lake
roleRef:
  kind: ClusterRole
  name: registry-viewer
  apiGroup: rbac.authorization.k8s.io
